### ISSUE TITLE
Random seeds in LdaCgsMulti

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/vsm#102]
[`LdaCgsMulti.train()`](https://github.com/inpho/vsm/blob/master/vsm/model/ldacgsmulti.py#L227) takes a `seeds` argument which expects either `None` or a list of seeds. If `None`, it broadcasts this to all threads. Should we also have this broadcast single seeds? Does this create threading issues?

**Comment by rrose1** [comment]
By broadcasting single seeds, do you mean copying the same seed to every thread?

`train` deconstructs the seed objects completely and sends the Mersenne Twister state descriptions contained therein as basic c-types. The behavior I'm supposing you mean could be accomplished by passing a list of references to the same seed. (For example, make a seed, wrap it in a list and multiply the list by the number of processors.)

**Comment by JaimieMurdock** [comment]
Issue incoherent¸ intent replaced by #107
