### ISSUE TITLE
invalid start byte errors with JSTOR files

### ISSUE THREAD

**Issue by colinallen** [inpho/vsm#125]
Many of the JSTOR files are throwing up during vsm init with this error:

UnicodeDecodeError: 'utf8' codec can't decode byte ... in position ...: invalid start byte

The message for file 685266.pdf has ... 0xf6 (= ö) in position 97...

The text file 685266.txt indeed has ö at that position (in middle of Schrödinger), but changing it to a plain 'o' allows everything to proceed.

**Comment by colinallen** [comment]
For 685552.txt same character (same author) in position 96.  Elsewhere in the document, the accents are missing from "Schrodinger".  This is first page content of JSTOR pdf, and is their rending of the JSTOR metadata.  So, my hypothesis is that their OCR txt content starts on the second page and has no unicode, but their first page is directly generated from their metadata, and they are including characters but not declaring the encoding correctly.

**Comment by colinallen** [comment]
Stripped out all the first pages and still getting similar errors, so not confined to initial page, apparently.

**Comment by JaimieMurdock** [comment]
Fixed via inpho/vsm v0.4a7. Now falls back to auto-detect encoding when UnicodeDecodeError is raised. This particular issue was due to the files being converted to `Latin-1` encoding by pdf2text, which may be a `LANG` variable issue.
