### ISSUE TITLE
windows pyenchant --htrc

### ISSUE THREAD

**Issue by colinallen** [inpho/vsm#134]
Windows user (Shawn) using --htrc flag for first time received error about pyenchant not being installed, so do dependencies need to be adjusted?

**Comment by JaimieMurdock** [comment]
We looked into this issue via e-mail and found that there is not a binary for PyEnchant on Windows 64-bit. I may look into fixing the upstream package, but another solution is to avoid dependencies on PyEnchant through modifying the relevant lines of [`vsm.extensions.htrc`](https://github.com/inpho/vsm/blob/master/vsm/extensions/htrc.py), especially given that there is already a fallback to WordNet.

See also: rfk/pyenchant#42, rfk/pyenchant#70
