### ISSUE TITLE
Deploying to Heroku issue

### ISSUE THREAD

**Issue by dhanush987** [inpho/vsm#157]
remote: Building source:
remote: 
remote: -----> Python app detected
remote:  !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.
remote:  !     Learn more: https://devcenter.heroku.com/articles/procfile
remote:  !     The latest version of Python 2 is python-2.7.14 (you are using python-2.7.12, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-2.7.14).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing python-2.7.12
remote: -----> Installing pip
remote: -----> Installing requirements with pip
remote:        Collecting numpy (from -r /tmp/build_c33b6b1b14b208c9891efbebedeb483c/requirements.txt (line 1))
remote:          Downloading numpy-1.13.3-cp27-cp27m-manylinux1_x86_64.whl (16.6MB)
remote:        Collecting bottle>=0.12 (from -r /tmp/build_c33b6b1b14b208c9891efbebedeb483c/requirements.txt (line 2))
remote:          Downloading bottle-0.12.13.tar.gz (70kB)
remote:        Collecting brewer2mpl>=1.4 (from -r /tmp/build_c33b6b1b14b208c9891efbebedeb483c/requirements.txt (line 3))
remote:          Downloading brewer2mpl-1.4.1-py2.py3-none-any.whl
remote:        Collecting pystache>=0.5.4 (from -r /tmp/build_c33b6b1b14b208c9891efbebedeb483c/requirements.txt (line 4))
remote:          Downloading pystache-0.5.4.tar.gz (75kB)
remote:        Collecting vsm from https://github.com/inpho/vsm/archive/master.zip#egg=vsm (from -r /tmp/build_c33b6b1b14b208c9891efbebedeb483c/requirements.txt (line 5))
remote:          Downloading https://github.com/inpho/vsm/archive/master.zip (664kB)
remote:            Complete output from command python setup.py egg_info:
remote:            Traceback (most recent call last):
remote:              File "<string>", line 1, in <module>
remote:              File "/tmp/pip-build-B63OW3/vsm/setup.py", line 3, in <module>
remote:                import numpy
remote:            ImportError: No module named numpy
remote:            
remote:            ----------------------------------------
remote:        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-B63OW3/vsm/
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to topicexplorer.
remote: 
To https://git.heroku.com/topicexplorer.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/topicexplorer.git'

**Comment by JaimieMurdock** [comment]
Hi, the supported environment is for Anaconda python which can be installed on Heroku using the [conda-buildpack](https://github.com/kennethreitz/conda-buildpack)

The reason for the error is that the installer expects `numpy` to already be installed in order to compile the C extension for the Gibbs Sampler, which dramatically speeds up the inference process for the topic modeling algorithms.

Please let me know if your Heroku instance works, and feel free to submit a pull request on the README.md if there is any documentation that would help!

**Comment by JaimieMurdock** [comment]
I found some a workaround for the C-extension compilation: https://stackoverflow.com/a/21621689

**Comment by JaimieMurdock** [comment]
Haven't heard anything back from @dhanush987. Closing.
