### ISSUE TITLE
Difficulty downloading vsm for python 3.7

### ISSUE THREAD

**Issue by kirtansakariya** [inpho/vsm#167]
https://github.com/inpho/topic-explorer/issues/341

**Comment by kirtansakariya** [comment]
Problem due to mismatch between `curexc` and `exc` variable names in `pystate.h` and `vsm/model/_cgs_update.cpp`.

**Comment by JaimieMurdock** [comment]
So it looks like the issue is that we version pinned the packages in `requirements.txt` This has also bitten us in  the main topic-explorer repository. Dependency managment is the next major task so we don't get hit by these upgrades. I'll do some work on that front next weekend.
