### ISSUE TITLE
Document dir hard coded in htrc.py

### ISSUE THREAD

**Issue by huangmimi** [inpho/vsm#74]
In running [12] of the ipython notebook https://github.com/inpho/vsm-demo-notebooks an error message prompted saying python can't find this file, "
/var/inphosemantics/data/20130101/htrc-anthropomorphism-1315/htrc-1315-metadata.json
"

The reason is because the path of this file is hard coded in htrc.py (vsm/vsm/extensions/htrc.py), and this can be enhanced in some way to avoid this above-mentioned error.

**Comment by JaimieMurdock** [comment]
This issue is fixed in the [topic-explorer](http://github.com/inpho/topic-explorer)'s htrc modules. The code referenced in the extensions of vsm should avoid this hard-coding of a particular example.
